services:
  penpot-frontend:
    image: penpotapp/frontend:latest
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Berlin
      - PENPOT_FLAGS=enable-registration enable-login-with-password
    depends_on:
      - penpot-backend
      - penpot-exporter
  penpot-backend:
    image: penpotapp/backend:latest
    environment:
      - TZ=Europe/Berlin
      - PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification
      - PENPOT_SECRET_KEY=${PENPOT_SECRET_KEY}
      - PENPOT_DATABASE_URI=postgresql://postgres:5432/penpot
      - PENPOT_DATABASE_USERNAME=penpot
      - PENPOT_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - PENPOT_REDIS_URI=redis://redis/0
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - PENPOT_TELEMETRY_ENABLED=false
      - PENPOT_PUBLIC_URI=https://${HOST}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - penpot_assets:/opt/data/assets
  penpot-exporter:
    image: penpotapp/exporter:latest
    environment:
      - TZ=Europe/Berlin
      - PENPOT_PUBLIC_URI=http://penpot-frontend
  postgres:
    image: postgres:18
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=penpot
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "penpot", "-U", "penpot"]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      backup.command: >-
        sh -lc 'mkdir -p /var/lib/postgresql/backups && \
        pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
          -f /var/lib/postgresql/backups/backup.sql'
  redis:
    image: redis:latest
    environment:
      - TZ=Europe/Berlin
volumes:
  penpot_assets:
  postgres_data:
