services:
  opensearch:
    image: opensearchproject/opensearch:3
    environment:
      - TZ=Europe/Berlin
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node-1
      - discovery.type=single-node
      - plugins.security.ssl.http.enabled=false
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - opensearch_data:/usr/share/opensearch/data
volumes:
  opensearch_data:
