services:
  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.10.6
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Berlin
      - CMD_DB_URL=postgres://hedgedoc:${POSTGRES_PASSWORD}@postgres:5432/hedgedoc
      - CMD_DOMAIN=${HOST}
      - CMD_PROTOCOL_USESSL=true
      - CMD_SESSION_SECRET=${SESSION_SECRET}
      - CMD_ALLOW_ANONYMOUS=false
    depends_on:
      - postgres
    volumes:
      - hedgedoc_uploads:/hedgedoc/public/uploads
  postgres:
    image: postgres:18
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=hedgedoc
    volumes:
      - postgres_data:/var/lib/postgresql
    labels:
      backup.command: >-
        sh -lc 'mkdir -p /var/lib/postgresql/backups && \
        pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
          -f /var/lib/postgresql/backups/backup.sql'
volumes:
  hedgedoc_uploads:
  postgres_data:
