services:
  langfuse:
    image: langfuse/langfuse:latest
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Berlin
      - DATABASE_URL=postgresql://langfuse:${POSTGRES_PASSWORD}@postgres:5432/langfuse
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=https://${HOST}
      - SALT=${SALT}
      - TELEMETRY_ENABLED=false
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:18
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=langfuse
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=langfuse
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER"
      interval: 2s
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql
    labels:
      backup.command: >-
        sh -lc 'mkdir -p /var/lib/postgresql/backups && \
        pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
          -f /var/lib/postgresql/backups/backup.sql'
volumes:
  postgres_data:
