services:
  listmonk:
    image: listmonk/listmonk:latest
    ports:
      - "9000:9000"
    command:
      - sh
      - -c
      - ./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''
    environment:
      - TZ=Europe/Berlin
      - LISTMONK_app__address=0.0.0.0:9000
      - LISTMONK_db__host=postgres
      - LISTMONK_db__port=5432
      - LISTMONK_db__user=listmonk
      - LISTMONK_db__password=${POSTGRES_PASSWORD}
      - LISTMONK_db__database=listmonk
      - LISTMONK_db__ssl_mode=disable
      - LISTMONK_ADMIN_USER=${ADMIN_USER}
      - LISTMONK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - listmonk_uploads:/listmonk/uploads
    depends_on:
      - postgres
  postgres:
    image: postgres:18
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=listmonk
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=listmonk
    volumes:
      - postgres_data:/var/lib/postgresql
    labels:
      backup.command: >-
        sh -lc 'mkdir -p /var/lib/postgresql/backups && \
        pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
          -f /var/lib/postgresql/backups/backup.sql'
volumes:
  listmonk_uploads:
  postgres_data:
