services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin
      - DATABASE_URL=postgres://miniflux:${POSTGRES_PASSWORD}@postgres:5432/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - BASE_URL=https://${HOST}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:18
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=miniflux
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql
    labels:
      backup.command: >-
        sh -lc 'mkdir -p /var/lib/postgresql/backups && \
        pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
          -f /var/lib/postgresql/backups/backup.sql'
volumes:
  postgres_data:
