services:
  vaultwarden:
    image: vaultwarden/server:latest
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Berlin
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=true
      - DATABASE_URL=postgresql://vaultwarden:${POSTGRES_PASSWORD}@postgres:5432/vaultwarden
      - DOMAIN=https://${HOST}
    depends_on:
      - postgres
    volumes:
      - vaultwarden_data:/data
  postgres:
    image: postgres:18
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=vaultwarden
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=vaultwarden
    volumes:
      - postgres_data:/var/lib/postgresql
    labels:
      backup.command: >-
        sh -lc 'mkdir -p /var/lib/postgresql/backups && \
        pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
          -f /var/lib/postgresql/backups/backup.sql'
volumes:
  vaultwarden_data:
  postgres_data:
