services:
  ntfy:
    image: binwiederhier/ntfy:latest
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Berlin
    command: serve
    volumes:
      - ntfy_data:/var/cache/ntfy
volumes:
  ntfy_data:
