services:
  mariadb:
    image: mariadb:lts
    environment:
      - TZ=Europe/Berlin
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${ADMIN_USER}
      - MARIADB_PASSWORD=${ADMIN_PASSWORD}
      - MARIADB_AUTO_UPGRADE=mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    labels:
      backup.command: >-
        sh -lc 'mkdir -p /var/lib/mysql/backups && \
        mariadb-dump -u "$MARIADB_USER" -p"$MARIADB_PASSWORD" --all-databases \
          > /var/lib/mysql/backups/backup.sql'
volumes:
  mariadb_data:
