services:
  typemill:
    image: kixote/typemill:latest
    ports:
      - "80:80"
    environment:
      TZ: Europe/Berlin
      TYPEMILL_PROXY_DETECTION: "true"
    volumes:
      - typemill_settings:/var/www/html/settings
      - typemill_media:/var/www/html/media
      - typemill_data:/var/www/html/data
      - typemill_cache:/var/www/html/cache
      - typemill_plugins:/var/www/html/plugins
      - typemill_content:/var/www/html/content
      - typemill_themes:/var/www/html/themes

volumes:
  typemill_settings:
  typemill_media:
  typemill_data:
  typemill_cache:
  typemill_plugins:
  typemill_content:
  typemill_themes: