services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    ports:
      - "3001:3001"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - uptimekuma_data:/app/data
volumes:
  uptimekuma_data:
