services:
  solr:
    image: solr:10
    environment:
      - TZ=Europe/Berlin
      - SOLR_HEAP=512m
      - SOLR_CONFIG_LIB_ENABLED=true
      - SOLR_MODULES=scripting,analysis-extras,langid,clustering,extraction
    volumes:
      - solr_data:/var/solr
volumes:
  solr_data:
