services:
  nocodb:
    image: nocodb/nocodb:latest
    ports:
      - "8080:8080"
    environment:
      - NC_DB=pg://postgres:5432?u=nocodb&p=${POSTGRES_PASSWORD}&d=nocodb
      - NC_AUTH_JWT_SECRET=${NC_AUTH_JWT_SECRET}
      - NC_PUBLIC_URL=https://${HOST}
      - NC_DISABLE_TELE=true
      - NC_INVITE_ONLY_SIGNUP=true
      - NC_REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - nocodb_data:/usr/app/data
  postgres:
    image: postgres:18
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=nocodb
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nocodb
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql
    labels:
      backup.command: >-
        sh -lc 'mkdir -p /var/lib/postgresql/backups && \
        pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" \
          -f /var/lib/postgresql/backups/backup.sql'
  redis:
    image: redis:8
    volumes:
      - redis_data:/data
volumes:
  nocodb_data:
  postgres_data:
  redis_data:
