services:
  rails:
    environment:
      SMTP_ADDRESS: ct-mail
      SMTP_PORT: "1025"
      SMTP_AUTHENTICATION: ""
      SMTP_ENABLE_STARTTLS_AUTO: "false"
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
  sidekiq:
    environment:
      SMTP_ADDRESS: ct-mail
      SMTP_PORT: "1025"
      SMTP_AUTHENTICATION: ""
      SMTP_ENABLE_STARTTLS_AUTO: "false"
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
