services:
  app:
    environment:
      MAIL_HOST: ct-mail
      MAIL_PORT: "1025"
      MAIL_ENCRYPTION: ""
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
  scheduler:
    environment:
      MAIL_HOST: ct-mail
      MAIL_PORT: "1025"
      MAIL_ENCRYPTION: ""
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
  queue:
    environment:
      MAIL_HOST: ct-mail
      MAIL_PORT: "1025"
      MAIL_ENCRYPTION: ""
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
