services:
  solidtime:
    image: solidtime/solidtime:latest
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Berlin
      - APP_URL=https://${HOST}
      - APP_KEY=${APP_KEY}
    volumes:
      - solidtime_data:/var/www/html/storage
volumes:
  solidtime_data:
